# SQLite version 3.x
#   gem install sqlite3
development:
    adapter: mysql2
    database: b4t_development
    encoding: utf8
    username: root
    password: qw34t678
    host: localhost
    socket: /var/run/mysqld/mysqld.sock

production:
    adapter: mysql2
    database: b4t_production
    encoding: utf8
    username: root
    password: alcohol2011
    host: localhost
    socket: /var/run/mysqld/mysqld.sock